/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class KKH_stb_image_JNI_wrap_STBimage */

#ifndef _Included_KKH_stb_image_JNI_wrap_STBimage
#define _Included_KKH_stb_image_JNI_wrap_STBimage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     KKH_stb_image_JNI_wrap_STBimage
 * Method:    imread_jni
 * Signature: (Ljava/lang/String;Z)LKKH/StdLib/Matk;
 */
JNIEXPORT jobject JNICALL Java_KKH_stb_1image_1JNI_1wrap_STBimage_imread_1jni
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     KKH_stb_image_JNI_wrap_STBimage
 * Method:    imwrite_jni
 * Signature: (Ljava/lang/String;LKKH/StdLib/Matk;II)Z
 */
JNIEXPORT jboolean JNICALL Java_KKH_stb_1image_1JNI_1wrap_STBimage_imwrite_1jni
  (JNIEnv *, jclass, jstring, jobject, jint, jint);

/*
 * Class:     KKH_stb_image_JNI_wrap_STBimage
 * Method:    imresize_jni
 * Signature: (LKKH/StdLib/Matk;II)LKKH/StdLib/Matk;
 */
JNIEXPORT jobject JNICALL Java_KKH_stb_1image_1JNI_1wrap_STBimage_imresize_1jni
  (JNIEnv *, jclass, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class KKH_stb_image_JNI_wrap_STBimage_ImageType */

#ifndef _Included_KKH_stb_image_JNI_wrap_STBimage_ImageType
#define _Included_KKH_stb_image_JNI_wrap_STBimage_ImageType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
